---
# Ansible role and collections requiremetns file.
# For installation from https://galaxy.ansible.com/

roles:
  - name: geerlingguy.firewall
    version: 2.5.0
    source: https://galaxy.ansible.com

  - name: geerlingguy.docker
    version: 3.1.2
    source: https://galaxy.ansible.com

  - name: geerlingguy.pip
    version: 2.0.0
    source: https://galaxy.ansible.com

  - name: geerlingguy.git
    version: 3.0.0
    source: https://galaxy.ansible.com

  - name: geerlingguy.certbot
    version: 4.0.0
    source: https://galaxy.ansible.com

collections:
  - name: community.docker
    version: 1.5.0
    source: https://galaxy.ansible.com
