version: "3.9"
services:
  # web:
  #   image: nginx:1.19.10
  #   container_name: nginx-pja
  #   restart: unless-stopped
  #   ports:
  #     - 80:80
  #     - 443:443
  #   networks:
  #     pja_network:
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      # - ...:/etc/letsencrypt

  app_api:
    image: and1er/pja-api:0.2.0
    container_name: pja-api
    restart: unless-stopped
    ports:
      - 127.0.0.1:5000:8080
    networks:
      pja_network:
    volumes:
      - /tmp/pja-api:/app/uploads

  app_exporter:
    image: and1er/pja-exporter:0.2.0
    container_name: pja-exporter
    restart: unless-stopped
    ports:
      - 127.0.0.1:6000:8080
    networks:
      pja_network:

networks:
  pja_network:
    name: pja_network
