name: Java API CI
on:
  push:
    paths:
      - 'app_api/**'

jobs:
  checkstyle_lint:
    runs-on: ubuntu-20.04
    name: Checkstyle lint
    steps:
    - name: Project Checkout
      uses: actions/checkout@v2

    - name: Run checkstyle
      uses: nikitasavinov/checkstyle-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: 'github-pr-check'
        tool_name: 'testtool'

  docker_build:
    needs: checkstyle_lint
    runs-on: ubuntu-20.04
    name: Docker Build

    defaults:
      run:
        working-directory: './app_api/'

    steps:
    - name: Project Checkout
      uses: actions/checkout@v2

    - name: Docker Build
      run: |
        docker build -t app_api:ci .
