name: Continuous Delivery

on:
  release:
    branches:
      - main
    types:
      - created
      - published
      - released

  # TODO: run after CI jobs
  # workflow_run:
  #   workflows:
  #     - Terraform CI
  #   types: 
  #     - completed

jobs:
  terraform_cd:
    name: Terraform CD
    runs-on: ubuntu-20.04

    env:
      TERRAFORM_VERSION: 0.15.0
    defaults:
      run:
        working-directory: './infrastructure/terraform-aws/'

    steps:
      - name: Project Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform v${{ env.TERRAFORM_VERSION }}
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Apply
        run: terraform apply -auto-approve
