name: Lint Project Files

on: [push]

jobs:
  super_linter:
    # https://github.com/marketplace/actions/super-linter
    name: Super Linter Stage
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
      - name: Run linter
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_GO: false
          
          # TODO: repair linters for Java. Disable due to Maven code errors
          VALIDATE_JAVA: false

          # Bash checks disabled due to 3rd party app_api/mvnw script errors and no own scripts for now.
          # TODO: if any own bash scripts will be add https://github.com/koalaman/shellcheck
          VALIDATE_BASH: false
          VALIDATE_BASH_EXEC: false
